/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.bijukunjummen.cloudfunction;

import com.github.bijukunjummen.cloudfunction.task.CloudFunctionInvokerTask;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.tasks.TaskProvider;

/**
 * Plugin to start the GCP Cloud Function Invoker
 */
public class GcpCloudfunctionGradlePlugin implements Plugin<Project> {
    private static final String CLOUDFUNCTION_INVOKER_NAME = "cloudfunctionInvoker";

    public void apply(Project project) {
        CloudFunctionInvokerExtension invokerExtension =
                project.getExtensions().create(CLOUDFUNCTION_INVOKER_NAME, CloudFunctionInvokerExtension.class, project);

        TaskProvider<CloudFunctionInvokerTask> buildImageTask = project.getTasks()
                .register("cloudfunctionInvoker", CloudFunctionInvokerTask.class, task -> {
                    task.setInvokerExtension(invokerExtension);
                });
    }
}
