/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.bijukunjummen.cloudfunction;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * Plugin to start the GCP Cloud Function Invoker
 */
public class GcpCloudfunctionGradlePluginPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("cloudfunction", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'org.bk.function.gradle.plugin.cloudfunction'"));
        });
    }
}
