/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.bijukunjummen.cloudfunction;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * A simple unit test for the 'org.bk.function.gradle.plugin.greeting' plugin.
 */
class GcpCloudfunctionGradlePluginPluginTest {
	@Test
	void pluginRegistersATask() {
		// Create a test project and apply the plugin
		Project project = ProjectBuilder.builder().build();
		project.getPlugins().apply("io.github.bijukunjummen.cloudfunction");

		// Verify the result
		assertNotNull(project.getTasks().findByName("cloudfunction"));
	}
}
